kind: pipeline
type: docker
name: build-and-push

trigger:
  branch:
    - main

steps:
  - name: build-push-image
    image: docker:27.5.1
    commands:
      - HARBOR_PASSWORD="Hao88.cloud!"
      - docker build -f Dockerfile -t ahao-drop:main .
      - docker images | grep ahao-drop
      - docker tag ahao-drop:main 192.168.8.6:3000/hao88/ahao-drop/ahao-drop:main # 打标签
      - echo "$HARBOR_PASSWORD" | docker login 192.168.8.6:3000 -u 52927295@qq.com --password-stdin # 登入
      - docker push 192.168.8.6:3000/hao88/ahao-drop/ahao-drop:main  # 推送
      - docker-compose up -d
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock