app:
  name: 'mc'
  version: '1.0.0'

options:
  port: ":8989"
  timeout: 10s

minio:
  address: "192.168.8.6:9768"
  accessKey: "ELUGN04RII6WD4K59DEM"
  secretKey: "ObhJpLZ6dNvR1sw2ZOU8EgvFCC9yuzEZIqS+m+Ul"
  bucket: "uchi"
  token: ""


