app:
  name: 'mc'
  version: '1.0.0'

options:
  port: ":80"
  timeout: 10s

minio:
  address: "192.168.8.6:9768"
  accessKey: "KGoLjPOAIGL3lWImIrVv"
  secretKey: "65DSz5AMWyqmyfEpboFKSWaVorgz1NjzzIaQ1heA"
  bucket: "uchi"
  token: ""


