version: '3.8'

services:
  app:
    container_name: ahao-drop
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "56776:80"
    networks:
      - dev
    environment:
      - ENV=dev
    command: " ./runner"
networks:
  dev:
    name: dev
    driver: bridge
    external: true